druker.server.*:
  type: config_entity
  label: 'Server'
  mapping:
    id:
      type: machine_name
      label: 'Machine name'
    label:
      type: required_label
      label: 'Label'
    hostname:
      type: string
      label: 'Hostname'
      constraints:
        NotBlank: {}
    status:
      type: boolean
      label: 'Enabled'
    default_refresh:
      type: integer
      label: 'Seconds between the worker asking for its schedule again'
      constraints:
        Range:
          min: 60
